repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
    -   id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        additional_dependencies: [
            "ruff[pycodestyle]",
            "ruff[pyflakes]",
            "ruff[isort]",
            "ruff[docstring-convention]"
        ]

-   repo: https://github.com/psf/black
    rev: 24.2.0  # Using the latest stable version
    hooks:
    -   id: black
        language_version: python3.13
        args: [--line-length=88, --fast]  # Black's default line length, with fast mode for quicker formatting
        types_or: [python, pyi, jupyter]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1  # Latest stable version
    hooks:
    -   id: isort
        args: ["--profile", "black", "--line-length", "88", "--filter-files"]  # Configure isort to be compatible with Black
        types_or: [python, pyi, jupyter]


